name = "todo-io"
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat"
]

main = "./functions/_worker.js"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.bindings]]
type = "kv_namespace"
binding = "ASSETS"
id = "__todo-io-workers_sites_assets" 