name = "todo-io"
compatibility_date = "2024-03-28"
compatibility_flags = [
  "nodejs_compat",
  "nodejs_module"
]

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build]
command = "npm run build"

[site]
bucket = "./build/client" 