name = "todo-io"
compatibility_date = "2024-09-23"
compatibility_flags = [
  "nodejs_compat",
  "nodejs_module"
]

main = "./functions/_worker.js"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"] 